# Generated by Django 5.0.6 on 2025-04-14 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_title', models.CharField(max_length=200)),
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=100)),
                ('year', models.CharField(choices=[('1st', 'First Year'), ('2nd', 'Second Year'), ('3rd', 'Third Year'), ('4th', 'Fourth Year')], max_length=4)),
                ('no_of_subjects', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='exam1.exam')),
            ],
        ),
    ]
