# Generated by Django 5.0.6 on 2025-04-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='no_of_subjects',
        ),
        migrations.AddField(
            model_name='exam',
            name='num_subjects',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='subject_names',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='year',
            field=models.IntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year')]),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
