# Generated by Django 5.0.6 on 2025-04-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam1', '0003_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='subject_max_marks',
            field=models.JSONField(default=list),
        ),
    ]
