# Generated by Django 5.0.6 on 2025-04-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam1', '0004_exam_subject_max_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='total_max_marks',
            field=models.IntegerField(default=0),
        ),
    ]
